### ISSUE TITLE
Unable to locate package openitcockpit/usr/share/openitcockpit/app

### ISSUE THREAD

**Issue by kurapas1** [it-novum/openITCOCKPIT#890] opened 2018-12-10 17:19 UTC
Hi Team,

am getting following error while installing openITcockpit

```
root@ZAPRKITNOVUM:~# apt-get install openitcockpit{,-common,-nagios,-statusengine-nagios,-message}/usr/share/openitcockpit/app/SETUP.sh
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package openitcockpit/usr/share/openitcockpit/app
E: Unable to locate package openitcockpit-common/usr/share/openitcockpit/app
E: Unable to locate package openitcockpit-nagios/usr/share/openitcockpit/app
E: Unable to locate package openitcockpit-statusengine-nagios/usr/share/openitcockpit/app
E: Unable to locate package openitcockpit-message/usr/share/openitcockpit/app
root@ZAPRKITNOVUM:~#
```
open for Teamviewer session too

**Comment by timo08** [comment] 2018-12-10 18:00
Hi @kurapas1,

please try to run the command without the path at the end:
apt-get install openitcockpit{,-common,-naemon,-statusengine-naemon,-message}

**Comment by nook24** [comment] 2018-12-11 06:37
Hi @kurapas1,
here's a short video which shows the installation: https://asciinema.org/a/161242

**Comment by kurapas1** [comment] 2018-12-11 07:23
> Hi @kurapas1,
> 
> please try to run the command without the path at the end:
> apt-get install openitcockpit{,-common,-naemon,-statusengine-naemon,-message}
> 
> Choose your system in the download section at https://openitcockpit.io/download to get installation instructions.

Hi Timo,

thanks, am getting below now if remove the path at the end.

Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 openitcockpit : Depends: openitcockpit-monitoring-plugins but it is not going to be installed
                 Recommends: mc but it is not installable
                 Recommends: phpmyadmin but it is not going to be installed
                 Recommends: grc but it is not installable
 openitcockpit-common : Depends: libcairo2 (>= 1.10.0) but it is not installable
                        Depends: libjpeg8 (>= 8c) but it is not installable
                        Depends: libpango-1.0-0 (>= 1.14.0) but it is not installable
                        Depends: libpangocairo-1.0-0 (>= 1.14.0) but it is not installable
                        Depends: php-dev but it is not going to be installed
                        Depends: mysql-server-5.7 but it is not going to be installed
                        Depends: librrds-perl but it is not installable
                        Depends: librrdp-perl but it is not installable
                        Depends: rrdtool but it is not installable
                        Depends: librrd-simple-perl but it is not installable
                        Depends: ssl-cert but it is not installable
                        Depends: php-rrd but it is not installable
                        Depends: php7.0-gd but it is not going to be installed
                        Depends: php-ssh2 but it is not installable
                        Depends: php7.0-mcrypt but it is not going to be installed
                        Depends: php7.0-zip but it is not going to be installed
                        Depends: php-gearman but it is not going to be installed
                        Depends: gearman-job-server but it is not installable
                        Depends: php7.0-imap but it is not going to be installed
                        Depends: openitcockpit-wkhtmltopdf but it is not going to be installed
                        Depends: php-redis but it is not installable
                        Depends: redis-server but it is not going to be installed
                        Depends: openitcockpit-mysql but it is not going to be installed
                        Depends: openitcockpit-release but it is not going to be installed
                        Recommends: sysstat but it is not going to be installed
 openitcockpit-statusengine-naemon : Depends: openitcockpit-mysql but it is not going to be installed
                                     Depends: gearman-job-server but it is not installable
                                     Depends: php-gearman but it is not going to be installed
                                     Depends: php-rrd but it is not installable
                                     Depends: libgearman-dev but it is not installable
                                     Depends: libjson-c-dev but it is not installable
                                     Depends: libglib2.0-dev but it is not going to be installed
                                     Recommends: gearman-tools but it is not installable
E: Unable to correct problems, you have held broken packages.

Thanks,
SIva

**Comment by kurapas1** [comment] 2018-12-11 07:33
> lsb_release -a

@nook24 

details below

root@ZAPRKITNOVUM:~# uname -a
Linux ZAPRKITNOVUM 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
root@ZAPRKITNOVUM:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
root@ZAPRKITNOVUM:~#

Thanks,
Siva

**Comment by nook24** [comment] 2018-12-11 07:37
Ok, looks good. Can you please run
`echo 'deb https://packages.openitcockpit.com/repositories/xenial xenial main' > /etc/apt/sources.list.d/openitcockpit.list`
and 
`apt-get update`

and check for any errors?

**Comment by kurapas1** [comment] 2018-12-11 07:45
> Ok, looks good. Can you please run
> `echo 'deb https://packages.openitcockpit.com/repositories/xenial xenial main' > /etc/apt/sources.list.d/openitcockpit.list`
> and
> `apt-get update`
> 
> and check for any errors?

am getting below error while doing update

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://za.archive.ubuntu.com/ubuntu xenial-backports InRelease: Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?)
W: Failed to fetch http://za.archive.ubuntu.com/ubuntu/dists/xenial-backports/InRelease  Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?)
E: Failed to fetch http://za.archive.ubuntu.com/ubuntu/dists/xenial/main/binary-amd64/by-hash/SHA256/76858a337b1665561a256cea6f7ef32515517754e3c5e54c1895cf29e1b41884  Hash Sum mismatch
E: Failed to fetch http://za.archive.ubuntu.com/ubuntu/dists/xenial/main/i18n/by-hash/SHA256/f514e12580e59b8f6ae10801a91f14708bdead04db91aa20fe9e2c0384413c67
E: Failed to fetch http://za.archive.ubuntu.com/ubuntu/dists/xenial-updates/main/binary-amd64/by-hash/SHA256/6f6be3a2957397a648d925a4b535a083673041aa6eca1e3ebd527d3d7b06b0e1  Hash Sum mismatch
E: Failed to fetch http://za.archive.ubuntu.com/ubuntu/dists/xenial-updates/universe/binary-amd64/by-hash/SHA256/7887d02606656ca59cb492f3c06fbc491780ea7fb1b7bbf317ae4a53570bc8a3
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/main/binary-i386/by-hash/SHA256/3b63ac1255d1d4cdb70a2bae70ebe026d208353c5eb156b0f8eaa7cc13051414  Hash Sum mismatch
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/restricted/binary-amd64/by-hash/SHA256/f1b4442b9dda392337d90c3ceeb33ce46339629547a8725f425e309d51edce49
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/universe/binary-amd64/by-hash/SHA256/a536a3d559897cd00ce24039943caa8b2d1113e11101be6cd41cafd8c716f401
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/universe/binary-i386/by-hash/SHA256/a4257d9dab0f056541bc1474729438540ef43080c294030023b9a2d154065bd7
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by nook24** [comment] 2018-12-11 07:57
There's definitely something broken with your internet connection.
Do you need to use an Proxy-Server or does your provider adds an transparent proxy?

Could you post the output of `curl -v  http://za.archive.ubuntu.com/ubuntu/dists/xenial-backports/InRelease` to https://gist.github.com/ and sendme the link?

**Comment by kurapas1** [comment] 2018-12-11 08:02
> There's definitely something broken with your internet connection.
> Do you need to use an Proxy-Server or does your provider adds an transparent proxy?
> 
> Could you post the output of `curl -v http://za.archive.ubuntu.com/ubuntu/dists/xenial-backports/InRelease` to https://gist.github.com/ and sendme the link?



am using proxy , below is the output of above cmd

root@ZAPRKITNOVUM:~# curl -v http://za.archive.ubuntu.com/ubuntu/dists/xenial-backports/InRelease to https://gist.github.com/
*   Trying 197.155.77.2...
*   Trying 2c0f:fe40:8001:10::2...
* Immediate connect fail for 2c0f:fe40:8001:10::2: Network is unreachable
*   Trying 2c0f:fe40:8001:10::2...
* Immediate connect fail for 2c0f:fe40:8001:10::2: Network is unreachable
*   Trying 2c0f:fe40:8001:10::2...
* Immediate connect fail for 2c0f:fe40:8001:10::2: Network is unreachable
^C
root@ZAPRKITNOVUM:~#

**Comment by nook24** [comment] 2018-12-11 08:19
> am using proxy , below is the output of above cmd

I guess you miss configured the proxy settings.

Can you please add the following lines to the file `/etc/environment`
````
http_proxy=http://PROXYIP:PROXY_PORT
HTTP_PROXY=http://PROXYIP:PROXY_PORT
https_proxy=http://PROXYIP:PROXY_PORT
HTTPS_PROXY=http://PROXYIP:PROXY_PORT
ftp_proxy=http://PROXYIP:PROXY_PORT
no_proxy=localhost,127.0.0.0/8,127.0.0.1
````
Add add the following line to the file `/etc/apt/apt.conf`
```
Acquire::http::Proxy "http://PROXYIP:PROXY_PORT";
```

and reboot your system.

Replace **PROXYIP** and **PROXY_PORT** with your values.
For example: `http://192.168.1.1:3128`

**Comment by kurapas1** [comment] 2018-12-11 08:58
> > am using proxy , below is the output of above cmd
> 
> I guess you miss configured the proxy settings.
> 
> Can you please add the following lines to the file `/etc/environment`
> 
> ```
> http_proxy=http://PROXYIP:PROXY_PORT
> HTTP_PROXY=http://PROXYIP:PROXY_PORT
> https_proxy=http://PROXYIP:PROXY_PORT
> HTTPS_PROXY=http://PROXYIP:PROXY_PORT
> ftp_proxy=http://PROXYIP:PROXY_PORT
> no_proxy=localhost,127.0.0.0/8,127.0.0.1
> ```
> Add add the following line to the file `/etc/apt/apt.conf`
> 
> ```
> Acquire::http::Proxy "http://PROXYIP:PROXY_PORT";
> ```
> and reboot your system.
> 
> Replace **PROXYIP** and **PROXY_PORT** with your values.
> For example: `http://192.168.1.1:3128`



am still getting following error

Err:4 http://za.archive.ubuntu.com/ubuntu xenial-backports InRelease             Splitting up /var/lib/apt/lists/partial/za.archive.ubuntu.com_ubuntu_dists_xenial-backports_InRelease into data and signature failed
  Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?)

**Comment by m4ximum** [comment] 2018-12-11 09:10
as @nook24 already mentioned, it seems like a misconfigured proxy either of your system or the providers proxy. You can still ask us about openitcockpit issues but at this point I will close this issue as this is not a problem of openITCOCKPIT

**Closed by m4ximum** 2018-12-11 09:10 UTC

**Comment by nook24** [comment] 2018-12-11 09:15
Unfortunately we reached a point, where I can't help you anymore to resolve your issue.

You have an major issue with your networking. Maybe this is caused by your company's network, maybe this is caused by VMware (NAT/Bright network) or KVM. Maybe this is caused by your ISP. So many options...

You should ask a local friend or colleague for help. If you resolve the network issue, and `apt-get update` and `apt-get instal htop vim` works without any issues, than your Ubuntu installation is configured right and you are ready to start with openITCOCKPIT installation.

This is not an issue related with openITCOCKPIT.

Good luck!
